### ISSUE TITLE
Cascading Style Sheets (CSS)

### ISSUE THREAD

**Issue by yane3628** [NuevoFoundation/web-basics-curriculum#10]
•	'important-section' does not match the code. Maybe it is referring to an 'id' instead of 'class.' If so, is this referring to id='info'? If so, we also have to change "In the first line" in the first sentence 
```
<div id="info">
      <h2>Information:</h2>
      <ul>      
        <li>I'm a Lab/Great Pyreneese mix</li>
        <li>I'm 1 year old</li>
        <li>I eat peanut butter you don't want</li>
        <li>I will protect you from squirrels</li>
      </ul>
    </div>    
```
•	Split this into two:

- In the first line we have a div with a class called important-section. All elements with class="important-section" will have the same color. We can also style a type of tag. In the header block of the CSS file, we tell the browser to color all the headers #0097A7 (which is the teal color). 

- In CSS, the syntax (or the way of writing a particular language) is to write what you want to style inside the curly braces { and }. Inside the curly braces, each line ends with a semicolon (the ; symbol).

**Comment by Sunny-Dee** [comment]
Oliver also updated this 💃
